services:
  nginx:
    image: nginx:alpine
    container_name: doonamis_nginx
    ports:
      - "80:80"       # Frontend
      - "8080:8080"   # Backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - back
    networks:
      - doonamis_network

  front:
    build: ./front
    container_name: doonamis_front
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start -- --host 0.0.0.0
    networks:
      - doonamis_network

  back:
    build: ./back
    container_name: doonamis_back
    expose:
      - "80"
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=doonamis_db
      - DB_USERNAME=doonamis_user
      - DB_PASSWORD=doonamis_pass
    networks:
      - doonamis_network

  mysql:
    image: mysql:latest
    container_name: doonamis_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=doonamis_db
      - MYSQL_USER=doonamis_user
      - MYSQL_PASSWORD=doonamis_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - doonamis_network

networks:
  doonamis_network:
    driver: bridge

volumes:
  mysql_data: